name: Build and deploy Node.js app to Azure Web App - herbie-nova

on:
  push:
    branches:
      - novaera
    paths-ignore:
      - 'README.md'
      - '.husky'
      - '**/*.csv'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install NPM UPDATE
        run: npm install -g npm@latest

      - name: Install NestJS CLI
        run: npm install -g @nestjs/cli

      - name: Install dependencies
        run: npm ci

      - name: Clean dist folder
        run: rm -rf dist

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Build application
        run: npm run build

      - name: Prepare package for deploy
        run: |
          mkdir packaged
          cp -r dist node_modules package*.json prisma packaged/
          cd packaged
          zip -r ../release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app-${{ github.run_id }}
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app-${{ github.run_id }}

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_56ED8410A4374539985CEB3C21DEBC17 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_33308C681BD34DE6BDE84467109FB7CB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_470AAA26E2FC4FF0B151E67959B66D5E }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'herbie-nova'
          slot-name: 'Production'
          package: release.zip
